---
- name: install ntp
  apt:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - ntp
  notify: restart ntp

- name: copy ntp default conf
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  notify: restart ntp
